{
	"version": 1500720069,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/phone-sheet0.png",
		"images/finger-sheet0.png",
		"images/finger-sheet1.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/target-sheet0.png",
		"images/bullet-sheet0.png",
		"images/fingertip-sheet0.png",
		"images/game1_icon-sheet0.png",
		"images/game2_icon-sheet0.png",
		"images/ally-sheet0.png",
		"images/player-sheet0.png",
		"images/line.png",
		"images/exit_icon-sheet0.png",
		"images/retry_icon-sheet0.png",
		"images/back_home.png",
		"images/back_g1.png",
		"images/home_logo-sheet0.png",
		"images/home_credits-sheet0.png",
		"images/game3_icon-sheet0.png",
		"images/game_over-sheet0.png",
		"images/you_win-sheet0.png",
		"images/you_lose-sheet0.png",
		"images/back_g2.png",
		"images/trap-sheet0.png",
		"media/blip-select 11.ogg",
		"media/blip-select 22.ogg",
		"media/explosion 1.ogg",
		"media/hit-hurt 2.ogg",
		"media/hit-hurt 6.ogg",
		"media/hit-hurt 7.ogg",
		"media/laser-shoot 1.ogg",
		"media/pickup-coin 3.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}